INSERT INTO emission_factor_list (list_name) VALUES
                                                 ('energy'),
                                                 ('vehicleFuels1'),
                                                 ('vehicleFuels2'),
                                                 ('vehicleFuels3'),
                                                 ('dispersedEmissions'),
                                                 ('boughtElectricalEnergy'),
                                                 ('boughtHeatEnergy'),
                                                 ('vans'),
                                                 ('rigidTruckMean'),
                                                 ('rigidTruckTonsFull'),
                                                 ('rigidTruckTonsHalf'),
                                                 ('articulatedTruckMean'),
                                                 ('articulatedTruckFull'),
                                                 ('articulatedTruckHalf'),
                                                 ('articulatedRigidMean'),
                                                 ('articulatedRigidFull'),
                                                 ('articulatedRigidHalf'),
                                                 ('transportBus'),
                                                 ('trains'),
                                                 ('planes'),
                                                 ('ships'),
                                                 ('businessTripsSmall'),
                                                 ('businessTripsBig'),
                                                 ('workHomeSmallVehicle'),
                                                 ('workHomeBigVehicle'),
                                                 ('waste'),
                                                 ('capacity');

INSERT INTO emission_factor (emission_factor_list_id, emission_type, factor) VALUES
                                                                                 (1, 'Biomass (kg)', 0.0008),
                                                                                 (1, 'Biomass (kWh)', 0.0002),
                                                                                 (1, 'Biometaan (kWh)', 0.0001),
                                                                                 (1, 'Biometaan (mᶟ)', 0.0011),
                                                                                 (1, 'Diisel (kWh)', 0.2647),
                                                                                 (1, 'Diisel (l)', 2.6239),
                                                                                 (1, 'Freesturvas (kWh)', 0.3840),
                                                                                 (1, 'Geotermaalenergia (kWh)', 0),
                                                                                 (1, 'Hüdroenergia (kWh)', 0),
                                                                                 (1, 'Kerge kütteõli (kg)', 3.1456),
                                                                                 (1, 'Kerge kütteõli (kWh)', 0.2664),
                                                                                 (1, 'Kivisüsi (kg)', 2.3651),
                                                                                 (1, 'Kivisüsi (kWh)', 0.3414),
                                                                                 (1, 'Maagaas (kWh)', 0.1990),
                                                                                 (1, 'Maagaas (mᶟ)', 1.8809),
                                                                                 (1, 'Olmejäätmed (kWh)', 0.1837),
                                                                                 (1, 'Põlevkivi (kWh)', 0.3681),
                                                                                 (1, 'Põlevkivi generaatorgaas (Kiviõli) (kWh)', 0.5931),
                                                                                 (1, 'Põlevkivi generaatorgaas (VKG) (kWh)', 0.6357),
                                                                                 (1, 'Põlevkivi poolkoksigaas (Enefit 280) (kWh)', 0.2597),
                                                                                 (1, 'Põlevkivi poolkoksigaas (Kiviõli) (kWh)', 0.2601),
                                                                                 (1, 'Põlevkivi poolkoksigaas (VKG Petr I) (kWh)', 0.2389),
                                                                                 (1, 'Põlevkivi poolkoksigaas (VKG Petr II) (kWh)', 0.2488),
                                                                                 (1, 'Põlevkivi poolkoksigaas (VKG Petr III) (kWh)', 0.2550),
                                                                                 (1, 'Põlevkiviõli kerge fraktsioon (kg)', 3.1350),
                                                                                 (1, 'Põlevkiviõli kerge fraktsioon (kWh)', 0.2668),
                                                                                 (1, 'Põlevkiviõli raske fraktsioon (kg)', 3.0361),
                                                                                 (1, 'Põlevkiviõli raske fraktsioon (kWh)', 0.2787),
                                                                                 (1, 'Päikeseenergia (kWh)', 0),
                                                                                 (1, 'Raske kütteõli (kg)', 3.0445),
                                                                                 (1, 'Raske kütteõli (kWh)', 0.2793),
                                                                                 (1, 'Roheline vesinik (kWh)', 0),
                                                                                 (1, 'Turbabrikett (kg)', 1.5629),
                                                                                 (1, 'Turbabrikett (kWh)', 0.3517),
                                                                                 (1, 'Tuuleenergia (kWh)', 0),
                                                                                 (1, 'Tuumaenergia (kWh)', 0),
                                                                                 (1, 'Tükkturvas (kWh)', 0.3697),
                                                                                 (1, 'Vedelgaas (LNG) (kWh)', 0.1990),
                                                                                 (1, 'Veeldatud naftagaas (LPG) (kWh)', 0.2287),
                                                                                 (2, 'Maanteesõiduki bensiin (l)', 2.24695),
                                                                                 (2, 'Maanteesõiduki biodiisel FAME (l)', 0.14845),
                                                                                 (2, 'Maanteesõiduki biodiisel HVO (l)', 0.00251),
                                                                                 (2, 'Maanteesõiduki biodiisel ME (l)', 0.01821),
                                                                                 (2, 'Maanteesõiduki diisel (l)', 2.63606),
                                                                                 (2, 'Maanteesõiduki surubiometaan bio-CNG (kg)', 0.01931),
                                                                                 (2, 'Maanteesõiduki surumaagaas CNG (kg)', 2.72689),
                                                                                 (2, 'Maanteesõiduki veeldatud naftagaas LPG (kg)', 2.91448),
                                                                                 (2, 'Rongidiisel (l)', 2.88988),
                                                                                 (2, 'Veesõiduk - laevakütus (l)', 2.64115),
                                                                                 (2, 'Õhusõiduk - lennukibensiin AVGAS 100LL (l)', 2.25100),
                                                                                 (2, 'Õhusõiduk - petrooli tüüpi reaktiivkütus (l)', 2.36126),
                                                                                 (3, 'Bensiin, kaubik (l)', 2.24614),
                                                                                 (3, 'Bensiin, mootorratas (l)', 2.28487),
                                                                                 (3, 'Bensiin, raskeveok (l)', 2.25509),
                                                                                 (3, 'Bensiin, sõiduauto (l)', 2.24632),
                                                                                 (3, 'Bio-CNG, kaubik (kg)', 0.01902),
                                                                                 (3, 'Bio-CNG, raskeveok/buss (kg)', 0.02062),
                                                                                 (3, 'Bio-CNG, sõiduauto (kg)', 0.01902),
                                                                                 (3, 'CNG, kaubik (kg)', 2.72659),
                                                                                 (3, 'CNG, raskeveok/buss (kg)', 2.72819),
                                                                                 (3, 'CNG, sõiduauto (kg)', 2.72659),
                                                                                 (3, 'Diisel, buss (l)', 2.64820),
                                                                                 (3, 'Diisel, kaubik (l)', 2.63620),
                                                                                 (3, 'Diisel, raskeveok (l)', 2.64820),
                                                                                 (3, 'Diisel, sõiduauto (l)', 2.64186),
                                                                                 (3, 'LPG, kaubik (kg)', 2.91448),
                                                                                 (3, 'LPG, raskeveok/buss (kg)', 2.91448),
                                                                                 (3, 'LPG, sõiduauto (kg)', 2.91448),
                                                                                 (4, 'Bensiin või diisel, suurus teadmata', 0.18930),
                                                                                 (4, 'Bensiin, keskmise suurusega (1,4–2,0 liitrine)', 0.19870),
                                                                                 (4, 'Bensiin, suur (üle 2,0-liitrine)', 0.25461),
                                                                                 (4, 'Bensiin, suurus teadmata', 0.19694),
                                                                                 (4, 'Bensiin, väike (kuni 1,4-liitrine bensiinimootor)', 0.16786),
                                                                                 (4, 'Diisel, keskmise suurusega (1,7–2,0-liitrine)', 0.16202),
                                                                                 (4, 'Diisel, suur (üle 2,0-liitrine)', 0.21729),
                                                                                 (4, 'Diisel, suurus teadmata', 0.18512),
                                                                                 (4, 'Diisel, väike (kuni 1,7-liitrine diiselmootor)', 0.16193),
                                                                                 (4, 'Hübriid, 1,4–2,0-liitrise bensiinimootoriga', 0.12447),
                                                                                 (4, 'Hübriid, kuni 1,4-liitrise bensiinimootoriga', 0.12003),
                                                                                 (4, 'Hübriid, suurus teadmata', 0.12689),
                                                                                 (4, 'Hübriid, üle 2,0-liitrise bensiinimootoriga', 0.13177),
                                                                                 (4, 'Kütus ja sõiduauto tüüp teadmata', 0.18618),
                                                                                 (4, 'Pistikhübriid (bensiin) (keskmistatud)', 0.14770),
                                                                                 (4, 'Pistikhübriid (diisel) (keskmistatud)', 0.13884),
                                                                                 (4, 'Surubiometaan (bio-CNG) (keskmistatud)', 0.00243),
                                                                                 (4, 'Surumaagaas (CNG) (keskmistatud)', 0.15971),
                                                                                 (4, 'Veeldatud naftagaas (LPG) (keskmistatud)', 0.16297);

INSERT INTO emission_factor (emission_factor_list_id, emission_type, factor) VALUES
                                                                                 (5, 'HCFE-235da2', 491),
                                                                                 (5, 'HFC-125 (R-125)', 3170),
                                                                                 (5, 'HFC-134 (R-134)', 1120),
                                                                                 (5, 'HFC-134a (R-134a)', 1300),
                                                                                 (5, 'HFC-143 (R-143)', 328),
                                                                                 (5, 'HFC-143a (R-143a)', 4800),
                                                                                 (5, 'HFC-152 (R-152)', 16),
                                                                                 (5, 'HFC-152a (R-152a)', 138),
                                                                                 (5, 'HFC-161 (R-161)', 4),
                                                                                 (5, 'HFC-227ea (R-227ea)', 3350),
                                                                                 (5, 'HFC-23 (R-23)', 12400),
                                                                                 (5, 'HFC-236cb (R-236cb)', 1210),
                                                                                 (5, 'HFC-236ea (R-236ea)', 1330),
                                                                                 (5, 'HFC-236fa (R-236fa)', 8060),
                                                                                 (5, 'HFC-245ca (R-245ca)', 716),
                                                                                 (5, 'HFC-245fa (R-245fa)', 858),
                                                                                 (5, 'HFC-32 (R-32)', 677),
                                                                                 (5, 'HFC-365mfc', 804),
                                                                                 (5, 'HFC-41 (R-41)', 116),
                                                                                 (5, 'HFC-43-10mee (R-4310)', 1650),
                                                                                 (5, 'HFE-125', 12400),
                                                                                 (5, 'HFE-134', 5560),
                                                                                 (5, 'HFE-143a', 523),
                                                                                 (5, 'HFE-236ca12 (HG-10)', 5350),
                                                                                 (5, 'HFE-245cb2', 654),
                                                                                 (5, 'HFE-245fa2', 812),
                                                                                 (5, 'HFE-338pcc13 (HG-01)', 2910),
                                                                                 (5, 'HFE-347mcc3', 530),
                                                                                 (5, 'HFE-347mcf2', 854),
                                                                                 (5, 'HFE-347pcf2', 889),
                                                                                 (5, 'HFE-356mec3', 387),
                                                                                 (5, 'HFE-356pcf2', 719),
                                                                                 (5, 'HFE-356pcc3', 413),
                                                                                 (5, 'HFE-356pcf3', 446),
                                                                                 (5, 'HFE-374pc2', 627),
                                                                                 (5, 'HFE-43-10pccc124 (H-Galden 1040x)', 2820),
                                                                                 (5, 'HFE-449sl (HFE-7100)', 421),
                                                                                 (5, 'HFE-569sf2 (HFE-7200)', 57),
                                                                                 (5, 'Lämmastiktrifluoriid', 16100),
                                                                                 (5, 'PFC-116 (perfluoroetaan)', 11100),
                                                                                 (5, 'PFC-14 (perfluorometaan)', 6630),
                                                                                 (5, 'PFC-218 (perfluoropropaan)', 8900),
                                                                                 (5, 'PFC-31-10 (perflourobutaan)', 9200),
                                                                                 (5, 'PFC-318 (perfluorotsüklobutaan)', 9540),
                                                                                 (5, 'PFC-41-12 (perfluoropentaan)', 8550),
                                                                                 (5, 'PFC-51-14 (perfluoroheksaan)', 7910),
                                                                                 (5, 'PFC-91-18 (perfluorodekaliin)', 7190),
                                                                                 (5, 'PFPMIE (perfluoropolümetüülisopropüül-eeter)', 9710),
                                                                                 (5, 'R-401A', 1130),
                                                                                 (5, 'R-401B', 1236),
                                                                                 (5, 'R-401C', 876),
                                                                                 (5, 'R-402A', 2571),
                                                                                 (5, 'R-402B', 2261),
                                                                                 (5, 'R-403B', 4457),
                                                                                 (5, 'R-404A', 3943),
                                                                                 (5, 'R-407A', 1923),
                                                                                 (5, 'R-407B', 2547),
                                                                                 (5, 'R-407C', 1624),
                                                                                 (5, 'R-407D', 1487),
                                                                                 (5, 'R-407E', 1425),
                                                                                 (5, 'R-407F', 1674),
                                                                                 (5, 'R-408A', 3257),
                                                                                 (5, 'R-410A', 1924),
                                                                                 (5, 'R-410B', 2048),
                                                                                 (5, 'R-411A', 1555),
                                                                                 (5, 'R-411B', 1659),
                                                                                 (5, 'R-4112', 8550),
                                                                                 (5, 'R-416A', 975),
                                                                                 (5, 'R-417A', 2127),
                                                                                 (5, 'R-417B', 2742),
                                                                                 (5, 'R-417C', 1643),
                                                                                 (5, 'R-419A', 2688),
                                                                                 (5, 'R-419B', 2162),
                                                                                 (5, 'R-420A', 1382),
                                                                                 (5, 'R-421A', 2385),
                                                                                 (5, 'R-421B', 2890),
                                                                                 (5, 'R-422A', 2847),
                                                                                 (5, 'R-422B', 2290),
                                                                                 (5, 'R-422C', 2795),
                                                                                 (5, 'R-422D', 2473),
                                                                                 (5, 'R-422E', 2350),
                                                                                 (5, 'R-423A', 2274),
                                                                                 (5, 'R-424A', 2212),
                                                                                 (5, 'R-425A', 1431),
                                                                                 (5, 'R-426A', 1371),
                                                                                 (5, 'R-427A', 2024),
                                                                                 (5, 'R-428A', 3417),
                                                                                 (5, 'R-429A', 15),
                                                                                 (5, 'R-430A', 106),
                                                                                 (5, 'R-431A', 42),
                                                                                 (5, 'R-434A', 3076),
                                                                                 (5, 'R-435A', 28),
                                                                                 (5, 'R-437A', 1639),
                                                                                 (5, 'R-438A', 2059),
                                                                                 (5, 'R-439A', 1829),
                                                                                 (5, 'R-444A', 89),
                                                                                 (5, 'R-445A', 118),
                                                                                 (5, 'R-500', 7564),
                                                                                 (5, 'R-503', 13300),
                                                                                 (5, 'R-507', 3985),
                                                                                 (5, 'R-507A', 3985),
                                                                                 (5, 'R-509', 4945),
                                                                                 (5, 'R-509A', 4945),
                                                                                 (5, 'R-512A', 196),
                                                                                 (5, 'Teadmata', 638),
                                                                                 (5, 'Trifluorometüülväävelpentafluoriid', 17400),
                                                                                 (5, 'Väävelheksafluoriid', 23500);

INSERT INTO emission_factor (emission_factor_list_id, emission_type, factor) VALUES
                                                                                 (6, 'Taastuvelekter (päritolutunnistusega: biomassist)', 0.00023),
                                                                                 (6, 'Taastuvelekter (päritolutunnistusega: päikese-, tuule- ja/või hüdroenergiast)', 0.000),
                                                                                 (6, 'Tavaelekter (segajääk)', 0.71518),
                                                                                 (6, 'Sõiduvahend (taastuvelekter)', 0.000),
                                                                                 (6, 'Sõiduvahend (tavaelekter)', 0.71518);

INSERT INTO emission_factor (emission_factor_list_id, emission_type, factor) VALUES
                                                                                 (7, 'Kaugküte - biomass (nt puiduhake, saepuru)', 0.00029),
                                                                                 (7, 'Kaugküte - Eesti keskmine', 0.15289),
                                                                                 (7, 'Kaugküte - freesturvas', 0.47999),
                                                                                 (7, 'Kaugküte - kerge kütteõli', 0.33306),
                                                                                 (7, 'Kaugküte - maagaas', 0.24880),
                                                                                 (7, 'Kaugküte - põlevkivi', 0.46007),
                                                                                 (7, 'Kaugküte - põlevkiviõli raske fraktsioon', 0.34836),
                                                                                 (7, 'Lokaalküte - biomass (puiduhake)', 0.00026),
                                                                                 (7, 'Lokaalküte - freesturvas', 0.480),
                                                                                 (7, 'Lokaalküte - kerge kütteõli', 0.29605),
                                                                                 (7, 'Lokaalküte - maagaas', 0.22115),
                                                                                 (7, 'Lokaalküte - põlevkiviõli raske fraktsioon', 0.30965);

INSERT INTO emission_factor (emission_factor_list_id, emission_type, factor) VALUES
                                                                                 (8, 'Kaubik (bensiin), km', 0.23222),
                                                                                 (8, 'Kaubik (bensiin), tonn-km', 0.19352),
                                                                                 (8, 'Kaubik (biodiisel FAME), km', 0.01303),
                                                                                 (8, 'Kaubik (biodiisel FAME), tonn-km', 0.01086),
                                                                                 (8, 'Kaubik (biodiisel HVO), km', 0.00022),
                                                                                 (8, 'Kaubik (biodiisel HVO), tonn-km', 0.00018),
                                                                                 (8, 'Kaubik (diisel), km', 0.23138),
                                                                                 (8, 'Kaubik (diisel), tonn-km', 0.19282),
                                                                                 (8, 'Kaubik (kütuseliik pole teada), km', 0.23144),
                                                                                 (8, 'Kaubik (kütuseliik pole teada), tonn-km', 0.19287),
                                                                                 (8, 'Kaubik (taastuvelekter), km', 0.000),
                                                                                 (8, 'Kaubik (taastuvelekter), tonn-km', 0.000),
                                                                                 (8, 'Kaubik (tavaelekter), km', 0.17880),
                                                                                 (8, 'Kaubik (tavaelekter), tonn-km', 0.149);

INSERT INTO emission_factor (emission_factor_list_id, emission_type, factor) VALUES
                                                                                 (9, 'Keskmine (7,5 t–20 t), biodiisel (FAME), km', 0.02986),
                                                                                 (9, 'Keskmine (7,5 t–20 t), biodiisel (HVO), km', 0.00050),
                                                                                 (9, 'Keskmine (7,5 t–20 t), diisel, km', 0.53017),
                                                                                 (9, 'Suur (>20 t), biodiisel (FAME), km', 0.03984),
                                                                                 (9, 'Suur (>20 t), biodiisel (HVO), km', 0.00067),
                                                                                 (9, 'Suur (>20 t), diisel, km', 0.70744),
                                                                                 (9, 'Suurus teadmata, biodiisel (FAME), km', 0.02929),
                                                                                 (9, 'Suurus teadmata, biodiisel (HVO), km', 0.00049),
                                                                                 (9, 'Suurus teadmata, diisel, km', 0.52002),
                                                                                 (9, 'Väike (<7,5 t), biodiisel (FAME), km', 0.01816),
                                                                                 (9, 'Väike (<7,5 t), biodiisel (HVO), km', 0.00031),
                                                                                 (9, 'Väike (<7,5 t), diisel, km', 0.32245);

INSERT INTO emission_factor (emission_factor_list_id, emission_type, factor) VALUES
                                                                                 (10, 'Keskmine (7,5 t–20 t), biodiisel (FAME), tonn-km', 0.00332),
                                                                                 (10, 'Keskmine (7,5 t–20 t), biodiisel (HVO), tonn-km', 0.00006),
                                                                                 (10, 'Keskmine (7,5 t–20 t), diisel, tonn-km', 0.05891),
                                                                                 (10, 'Suur (>20 t), biodiisel (FAME), tonn-km', 0.00210),
                                                                                 (10, 'Suur (>20 t), biodiisel (HVO), tonn-km', 0.00004),
                                                                                 (10, 'Suur (>20 t), diisel, tonn-km', 0.03723),
                                                                                 (10, 'Suurus teadmata, biodiisel (FAME), tonn-km', 0.00353),
                                                                                 (10, 'Suurus teadmata, biodiisel (HVO), tonn-km', 0.00006),
                                                                                 (10, 'Suurus teadmata, diisel, tonn-km', 0.06276),
                                                                                 (10, 'Väike (<7,5 t), biodiisel (FAME), tonn-km', 0.00519),
                                                                                 (10, 'Väike (<7,5 t), biodiisel (HVO), tonn-km', 0.00009),
                                                                                 (10, 'Väike (<7,5 t), diisel, tonn-km', 0.09213);

INSERT INTO emission_factor (emission_factor_list_id, emission_type, factor) VALUES
                                                                                 (11, 'Keskmine (7,5 t–20 t), biodiisel (FAME), tonn-km', 0.00663),
                                                                                 (11, 'Keskmine (7,5 t–20 t), biodiisel (HVO), tonn-km', 0.00011),
                                                                                 (11, 'Keskmine (7,5 t–20 t), diisel, tonn-km', 0.11782),
                                                                                 (11, 'Suur (>20 t), biodiisel (FAME), tonn-km', 0.00419),
                                                                                 (11, 'Suur (>20 t), biodiisel (HVO), tonn-km', 0.00134),
                                                                                 (11, 'Suur (>20 t), diisel, tonn-km', 0.07447),
                                                                                 (11, 'Suurus teadmata, biodiisel (FAME), tonn-km', 0.00707),
                                                                                 (11, 'Suurus teadmata, biodiisel (HVO), tonn-km', 0.00054),
                                                                                 (11, 'Suurus teadmata, diisel, tonn-km', 0.12551),
                                                                                 (11, 'Väike (<7,5 t), biodiisel (FAME), tonn-km', 0.01038),
                                                                                 (11, 'Väike (<7,5 t), biodiisel (HVO), tonn-km', 0.00018),
                                                                                 (11, 'Väike (<7,5 t), diisel, tonn-km', 0.18426);

INSERT INTO emission_factor (emission_factor_list_id, emission_type, factor) VALUES
                                                                                 (12, 'Keskmine (>3,5–32 t), biodiisel (FAME), km', 0.03452),
                                                                                 (12, 'Keskmine (>3,5–32 t), biodiisel (HVO), km', 0.00058),
                                                                                 (12, 'Keskmine (>3,5–32 t), diisel, km', 0.61296),
                                                                                 (12, 'Suur (>32 t), biodiisel (FAME), km', 0.04487),
                                                                                 (12, 'Suur (>32 t), biodiisel (HVO), km', 0.00076),
                                                                                 (12, 'Suur (>32 t), diisel, km', 0.79680),
                                                                                 (12, 'Suurus teadmata, biodiisel (FAME), km', 0.03970),
                                                                                 (12, 'Suurus teadmata, biodiisel (HVO), km', 0.00067),
                                                                                 (12, 'Suurus teadmata, diisel, km', 0.70488);

INSERT INTO emission_factor (emission_factor_list_id, emission_type, factor) VALUES
                                                                                 (13, 'Keskmine (>3,5–32 t), biodiisel (FAME), tonn-km', 0.00138),
                                                                                 (13, 'Keskmine (>3,5–32 t), biodiisel (HVO), tonn-km', 0.00002),
                                                                                 (13, 'Keskmine (>3,5–32 t), diisel, tonn-km', 0.02452),
                                                                                 (13, 'Suur (>32 t), biodiisel (FAME), tonn-km', 0.00112),
                                                                                 (13, 'Suur (>32 t), biodiisel (HVO), tonn-km', 0.00002),
                                                                                 (13, 'Suur (>32 t), diisel, tonn-km', 0.01992),
                                                                                 (13, 'Suurus teadmata, biodiisel (FAME), tonn-km', 0.00125),
                                                                                 (13, 'Suurus teadmata, biodiisel (HVO), tonn-km', 0.00002),
                                                                                 (13, 'Suurus teadmata, diisel, tonn-km', 0.02222);

INSERT INTO emission_factor (emission_factor_list_id, emission_type, factor) VALUES
                                                                                 (14, 'Keskmine (>3,5–32 t), biodiisel (FAME), tonn-km', 0.00276),
                                                                                 (14, 'Keskmine (>3,5–32 t), biodiisel (HVO), tonn-km', 0.00005),
                                                                                 (14, 'Keskmine (>3,5–32 t), diisel, tonn-km', 0.04904),
                                                                                 (14, 'Suur (>32 t), biodiisel (FAME), tonn-km', 0.00224),
                                                                                 (14, 'Suur (>32 t), biodiisel (HVO), tonn-km', 0.00004),
                                                                                 (14, 'Suur (>32 t), diisel, tonn-km', 0.03984),
                                                                                 (14, 'Suurus teadmata, biodiisel (FAME), tonn-km', 0.00250),
                                                                                 (14, 'Suurus teadmata, biodiisel (HVO), tonn-km', 0.00004),
                                                                                 (14, 'Suurus teadmata, diisel, tonn-km', 0.04444);

INSERT INTO emission_factor (emission_factor_list_id, emission_type, factor) VALUES
                                                                                 (15, 'Veoauto tüüp ja suurus teadmata, biodiisel (FAME), km', 0.03449),
                                                                                 (15, 'Veoauto tüüp ja suurus teadmata, biodiisel (HVO), km', 0.00058),
                                                                                 (15, 'Veoauto tüüp ja suurus teadmata, diisel, km', 0.61245);

INSERT INTO emission_factor (emission_factor_list_id, emission_type, factor) VALUES
                                                                                 (16, 'Veoauto tüüp ja suurus teadmata, biodiisel (FAME), tonn-km', 0.00239),
                                                                                 (16, 'Veoauto tüüp ja suurus teadmata, biodiisel (HVO), tonn-km', 0.00004),
                                                                                 (16, 'Veoauto tüüp ja suurus teadmata, diisel, tonn-km', 0.04249);

INSERT INTO emission_factor (emission_factor_list_id, emission_type, factor) VALUES
                                                                                 (17, 'Veoauto tüüp ja suurus teadmata, biodiisel (FAME), tonn-km', 0.00479),
                                                                                 (17, 'Veoauto tüüp ja suurus teadmata, biodiisel (HVO), tonn-km', 0.00029),
                                                                                 (17, 'Veoauto tüüp ja suurus teadmata, diisel, tonn-km', 0.08498);

INSERT INTO emission_factor (emission_factor_list_id, emission_type, factor) VALUES
                                                                                 (18, 'Buss', 0.66205),
                                                                                 (18, 'Väikebuss', 0.23183);

INSERT INTO emission_factor (emission_factor_list_id, emission_type, factor) VALUES
                                                                                 (19, 'Diiselveduriga kaubarong (keskmine, Balti riigid + Venemaa)', 0.02317),
                                                                                 (19, 'Kaubarong (keskmine, muu Euroopa)', 0.02782);

INSERT INTO emission_factor (emission_factor_list_id, emission_type, factor) VALUES
                                                                                 (20, 'Kaubalennuk (keskmistatud)', 1.01890);

INSERT INTO emission_factor (emission_factor_list_id, emission_type, factor) VALUES
                                                                                 (21, 'Kemikaalitanker (keskmistatud)', 0.01032),
                                                                                 (21, 'Konteinerilaev (keskmistatud)', 0.01614),
                                                                                 (21, 'Külmutatud kauba laev (kõik DWT-d)', 0.01308),
                                                                                 (21, 'LNG tanker (keskmistatud)', 0.01155),
                                                                                 (21, 'LPG tanker (keskmistatud)', 0.01038),
                                                                                 (21, 'Naftatanker (keskmistatud)', 0.00457),
                                                                                 (21, 'Parvlaev (reisi-kaubalaev, nt Tallinn-Helsingi/Stockholm)', 0.08200),
                                                                                 (21, 'Puistlastilaev (bulker) (keskmistatud)', 0.00354),
                                                                                 (21, 'Ro-ro/ro-pax laev (2000+ LM)', 0.05019),
                                                                                 (21, 'Ro-ro/ro-pax laev (valdav osa Eesti ja Põhjamaade vahel sõitvatest laevadest) (kuni 2000 LM)', 0.06114),
                                                                                 (21, 'Sõidukite transpordilaev (keskmistatud)', 0.03858),
                                                                                 (21, 'Tootetanker (keskmistatud)', 0.00903),
                                                                                 (21, 'Üldkaubalaev (keskmistatud)', 0.01323);

INSERT INTO emission_factor (emission_factor_list_id, emission_type, factor) VALUES
                                                                                 (22, 'Mootorratas 4-taktiline <250 cm³ (bensiin)', 0.06899),
                                                                                 (22, 'Mootorratas 4-taktiline >750 cm³ (bensiin)', 0.13093),
                                                                                 (22, 'Mootorratas 4-taktiline 250–750 cm³ (bensiin)', 0.12520),
                                                                                 (22, 'Mopeed 4-taktiline <50 cm³ (bensiin)', 0.05739),
                                                                                 (22, 'Sõiduauto (bio-CNG)', 0.00243),
                                                                                 (22, 'Sõiduauto (maagaas CNG)', 0.15971),
                                                                                 (22, 'Sõiduauto (pistikhübriid: bensiin/taastuvelekter) (keskmistatud)', 0.14770),
                                                                                 (22, 'Sõiduauto (pistikhübriid: bensiin/tavaelekter) (keskmistatud)', 0.18346),
                                                                                 (22, 'Sõiduauto (pistikhübriid: diisel/taastuvelekter) (keskmistatud)', 0.13884),
                                                                                 (22, 'Sõiduauto (pistikhübriid: diisel/tavaelekter) (keskmistatud)', 0.17460),
                                                                                 (22, 'Sõiduauto (taastuvelekter)', 0),
                                                                                 (22, 'Sõiduauto (tavaelekter)', 0.14304),
                                                                                 (22, 'Sõiduauto (veeldatud naftagaas LPG)', 0.16297),
                                                                                 (22, 'Sõiduauto, keskmise suurusega (bensiin)', 0.19870),
                                                                                 (22, 'Sõiduauto, keskmise suurusega (biodiisel FAME)', 0.00912),
                                                                                 (22, 'Sõiduauto, keskmise suurusega (biodiisel HVO)', 0.00015),
                                                                                 (22, 'Sõiduauto, keskmise suurusega (diisel)', 0.16202),
                                                                                 (22, 'Sõiduauto, keskmise suurusega (hübriid: bensiin/elekter)', 0.12447),
                                                                                 (22, 'Sõiduauto, suur (bensiin)', 0.25461),
                                                                                 (22, 'Sõiduauto, suur (biodiisel FAME)', 0.01224),
                                                                                 (22, 'Sõiduauto, suur (biodiisel HVO)', 0.00021),
                                                                                 (22, 'Sõiduauto, suur (diisel)', 0.21729),
                                                                                 (22, 'Sõiduauto, suur (hübriid: bensiin/elekter)', 0.13177),
                                                                                 (22, 'Sõiduauto, suurus ja kütus teadmata', 0.18618),
                                                                                 (22, 'Sõiduauto, suurus teadmata (bensiin või diisel)', 0.18930),
                                                                                 (22, 'Sõiduauto, suurus teadmata (bensiin)', 0.19694),
                                                                                 (22, 'Sõiduauto, suurus teadmata (biodiisel FAME)', 0.01042),
                                                                                 (22, 'Sõiduauto, suurus teadmata (biodiisel HVO)', 0.00018),
                                                                                 (22, 'Sõiduauto, suurus teadmata (diisel)', 0.18512),
                                                                                 (22, 'Sõiduauto, suurus teadmata (hübriid: bensiin/elekter)', 0.12689),
                                                                                 (22, 'Sõiduauto, väike (bensiin)', 0.16786),
                                                                                 (22, 'Sõiduauto, väike (biodiisel FAME)', 0.00912),
                                                                                 (22, 'Sõiduauto, väike (biodiisel HVO)', 0.00015),
                                                                                 (22, 'Sõiduauto, väike (diisel)', 0.16193),
                                                                                 (22, 'Sõiduauto, väike (hübriid: bensiin/elekter)', 0.12003),
                                                                                 (22, 'Takso, keskmine', 0.18930);

INSERT INTO emission_factor (emission_factor_list_id, emission_type, factor) VALUES
                                                                                 (23, 'Buss, kaugliin (Eesti ja rahvusvaheline)', 0.03563),
                                                                                 (23, 'Buss, kohalik liin (muud riigid)', 0.10227),
                                                                                 (23, 'Buss, linnaliin (Eesti)', 0.13981),
                                                                                 (23, 'Buss, maakondlik liin (Eesti)', 0.10648),
                                                                                 (23, 'Lennuk, Euroopa-sisene lend (kuni 3700 km), keskmine', 0.15353),
                                                                                 (23, 'Lennuk, Euroopa-sisene lend (kuni 3700 km), tava-/turistiklass', 0.15102),
                                                                                 (23, 'Lennuk, Euroopa-sisene lend (kuni 3700 km), äriklass', 0.22652),
                                                                                 (23, 'Lennuk, lend väljapoole Euroopat (üle 3700 km), esimene klass', 0.59147),
                                                                                 (23, 'Lennuk, lend väljapoole Euroopat (üle 3700 km), keskmine', 0.19309),
                                                                                 (23, 'Lennuk, lend väljapoole Euroopat (üle 3700 km), tava-/turistiklass', 0.14787),
                                                                                 (23, 'Lennuk, lend väljapoole Euroopat (üle 3700 km), äriklass', 0.42882),
                                                                                 (23, 'Lennuk, riigisisene lend, tava-/turistiklass', 0.24587),
                                                                                 (23, 'Parvlaev, reisi-kaubalaev (nt Tallinn-Helsingi/Stockholm)', 0.01874),
                                                                                 (23, 'Rong (muud riigid, sh rahvusvaheline rong, elektriallikas pole teada)', 0.00446),
                                                                                 (23, 'Rong (muud riigid, taastuvelekter)', 0),
                                                                                 (23, 'Rong, Eesti linnalähirong (elektrirong)', 0),
                                                                                 (23, 'Rong, Eesti-sisene kaugliin (diiselrong)', 0.08179),
                                                                                 (23, 'Takso, keskmine', 0.12763),
                                                                                 (23, 'Tramm, metroo (muud riigid, elektri allikas pole teada)', 0.02800),
                                                                                 (23, 'Tramm, metroo (muud riigid, taastuvelekter)', 0),
                                                                                 (23, 'Tramm, troll (Eesti)', 0);

INSERT INTO emission_factor (emission_factor_list_id, emission_type, factor) VALUES
                                                                                 (24, 'Elektrijalgratas/-tõukeratas (tavaelekter)', 0.00887),
                                                                                 (24, 'Elektrijalgratas/-tõukeratas, sh sõidujagamisplatvormidelt (taastuvelekter)', 0),
                                                                                 (24, 'Jalgratas', 0),
                                                                                 (24, 'Jalgsi liikumine', 0),
                                                                                 (24, 'Mootorratas 4-taktiline <250 cm³ (bensiin)', 0.06899),
                                                                                 (24, 'Mootorratas 4-taktiline >750 cm³ (bensiin)', 0.13093),
                                                                                 (24, 'Mootorratas 4-taktiline 250–750 cm³ (bensiin)', 0.12520),
                                                                                 (24, 'Mopeed 4-taktiline <50 cm³ (bensiin)', 0.05739),
                                                                                 (24, 'Sõiduauto (bio-CNG)', 0.00243),
                                                                                 (24, 'Sõiduauto (maagaas CNG)', 0.15971),
                                                                                 (24, 'Sõiduauto (pistikhübriid: bensiin/taastuvelekter) (keskmistatud)', 0.14770),
                                                                                 (24, 'Sõiduauto (pistikhübriid: bensiin/tavaelekter) (keskmistatud)', 0.13884),
                                                                                 (24, 'Sõiduauto (pistikhübriid: diisel/taastuvelekter) (keskmistatud)', 0.18346),
                                                                                 (24, 'Sõiduauto (pistikhübriid: diisel/tavaelekter) (keskmistatud)', 0.17460),
                                                                                 (24, 'Sõiduauto (taastuvelekter)', 0.00000),
                                                                                 (24, 'Sõiduauto (tavaelekter)', 0.14304),
                                                                                 (24, 'Sõiduauto (veeldatud naftagaas LPG)', 0.16297),
                                                                                 (24, 'Sõiduauto, keskmise suurusega (bensiin)', 0.19870),
                                                                                 (24, 'Sõiduauto, keskmise suurusega (biodiisel FAME)', 0.00912),
                                                                                 (24, 'Sõiduauto, keskmise suurusega (biodiisel HVO)', 0.00015),
                                                                                 (24, 'Sõiduauto, keskmise suurusega (diisel)', 0.16202),
                                                                                 (24, 'Sõiduauto, keskmise suurusega (hübriid: bensiin/elekter)', 0.12447),
                                                                                 (24, 'Sõiduauto, suur (bensiin)', 0.25461),
                                                                                 (24, 'Sõiduauto, suur (biodiisel FAME)', 0.01224),
                                                                                 (24, 'Sõiduauto, suur (biodiisel HVO)', 0.00021),
                                                                                 (24, 'Sõiduauto, suur (diisel)', 0.21729),
                                                                                 (24, 'Sõiduauto, suur (hübriid: bensiin/elekter)', 0.13177),
                                                                                 (24, 'Sõiduauto, suurus ja kütus teadmata', 0.18618),
                                                                                 (24, 'Sõiduauto, suurus teadmata (bensiin või diisel)', 0.18930),
                                                                                 (24, 'Sõiduauto, suurus teadmata (bensiin)', 0.19694),
                                                                                 (24, 'Sõiduauto, suurus teadmata (biodiisel FAME)', 0.01042),
                                                                                 (24, 'Sõiduauto, suurus teadmata (biodiisel HVO)', 0.00018),
                                                                                 (24, 'Sõiduauto, suurus teadmata (diisel)', 0.18512),
                                                                                 (24, 'Sõiduauto, suurus teadmata (hübriid: bensiin/elekter)', 0.12689),
                                                                                 (24, 'Sõiduauto, väike (bensiin)', 0.16786),
                                                                                 (24, 'Sõiduauto, väike (biodiisel FAME)', 0.00912),
                                                                                 (24, 'Sõiduauto, väike (biodiisel HVO)', 0.00015),
                                                                                 (24, 'Sõiduauto, väike (diisel)', 0.16193),
                                                                                 (24, 'Sõiduauto, väike (hübriid: bensiin/elekter)', 0.12003),
                                                                                 (24, 'Takso, keskmine', 0.18930);

INSERT INTO emission_factor (emission_factor_list_id, emission_type, factor) VALUES
                                                                                 (25, 'Buss, linnaliin', 0.13981),
                                                                                 (25, 'Buss, maakondlik liin', 0.10648),
                                                                                 (25, 'Rong, diisel- ja elektrirongide keskmine (rongitüüp pole teada)', 0.02330),
                                                                                 (25, 'Rong, diiselrong', 0.08179),
                                                                                 (25, 'Rong, linnalähirong (elektrirong)', 0),
                                                                                 (25, 'Takso, keskmine', 0.12763),
                                                                                 (25, 'Tramm', 0),
                                                                                 (25, 'Troll', 0);

INSERT INTO emission_factor (emission_factor_list_id, emission_type, factor) VALUES
                                                                                 (26, 'Liigiti kogutud biojäätmed', 28.68879),
                                                                                 (26, 'Liigiti kogutud klaaspakend', 28.68879),
                                                                                 (26, 'Liigiti kogutud paber ja kartong', 28.68879),
                                                                                 (26, 'Liigiti kogutud segapakend', 28.68879),
                                                                                 (26, 'Segaolmejäätmed, lõppkäitlusviis pole teada', 620),
                                                                                 (26, 'Segaolmejäätmed, prügilasse ladestamine', 620),
                                                                                 (26, 'Segaolmejäätmed, põletamine', 547.68879);

INSERT INTO emission_factor (emission_factor_list_id, emission_type, factor) VALUES
                                                                                 (27, 'Keskmine km', 0),
                                                                                 (27, 'Täiskoorem', 1),
                                                                                 (27, 'Osalise koormusega', 2);