INSERT INTO emission_factor_list (list_name) VALUES
                                                 ('energy'),
                                                 ('vehicleFuels1'),
                                                 ('vehicleFuels2'),
                                                 ('vehicleFuels3'),
                                                 ('hajusHeitmed'),
                                                 ('ostetudElektrienergia'),
                                                 ('ostetudSoojusEnergia'),
                                                 ('transport'),
                                                 ('tooreisid'),
                                                 ('tooleKoju'),
                                                 ('kojuToole');

INSERT INTO emission_factor (emission_factor_list_id, emission_type, factor) VALUES
                                                                                 (1, 'Biomass (kg)', 0.0008),
                                                                                 (1, 'Biomass (kWh)', 0.0002),
                                                                                 (1, 'Biometaan (kWh)', 0.0001),
                                                                                 (1, 'Biometaan (mᶟ)', 0.0011),
                                                                                 (1, 'Diisel (kWh)', 0.2647),
                                                                                 (1, 'Diisel (l)', 2.6239),
                                                                                 (1, 'Freesturvas (kWh)', 0.3840),
                                                                                 (1, 'Geotermaalenergia (kWh)', 0.0000),
                                                                                 (1, 'Hüdroenergia (kWh)', 0.0000),
                                                                                 (1, 'Kerge kütteõli (kg)', 3.1456),
                                                                                 (1, 'Kerge kütteõli (kWh)', 0.2664),
                                                                                 (1, 'Kivisüsi (kg)', 2.3651),
                                                                                 (1, 'Kivisüsi (kWh)', 0.3414),
                                                                                 (1, 'Maagaas (kWh)', 0.1990),
                                                                                 (1, 'Maagaas (mᶟ)', 1.8809),
                                                                                 (1, 'Olmejäätmed (kWh)', 0.1837),
                                                                                 (1, 'Põlevkivi (kWh)', 0.3681),
                                                                                 (1, 'Põlevkivi generaatorgaas (Kiviõli) (kWh)', 0.5931),
                                                                                 (1, 'Põlevkivi generaatorgaas (VKG) (kWh)', 0.6357),
                                                                                 (1, 'Põlevkivi poolkoksigaas (Enefit 280) (kWh)', 0.2597),
                                                                                 (1, 'Põlevkivi poolkoksigaas (Kiviõli) (kWh)', 0.2601),
                                                                                 (1, 'Põlevkivi poolkoksigaas (VKG Petr I) (kWh)', 0.2389),
                                                                                 (1, 'Põlevkivi poolkoksigaas (VKG Petr II) (kWh)', 0.2488),
                                                                                 (1, 'Põlevkivi poolkoksigaas (VKG Petr III) (kWh)', 0.2550),
                                                                                 (1, 'Põlevkiviõli kerge fraktsioon (kg)', 3.1350),
                                                                                 (1, 'Põlevkiviõli kerge fraktsioon (kWh)', 0.2668),
                                                                                 (1, 'Põlevkiviõli raske fraktsioon (kg)', 3.0361),
                                                                                 (1, 'Põlevkiviõli raske fraktsioon (kWh)', 0.2787),
                                                                                 (1, 'Päikeseenergia (kWh)', 0.0000),
                                                                                 (1, 'Raske kütteõli (kg)', 3.0445),
                                                                                 (1, 'Raske kütteõli (kWh)', 0.2793),
                                                                                 (1, 'Roheline vesinik (kWh)', 0.0000),
                                                                                 (1, 'Turbabrikett (kg)', 1.5629),
                                                                                 (1, 'Turbabrikett (kWh)', 0.3517),
                                                                                 (1, 'Tuuleenergia (kWh)', 0.0000),
                                                                                 (1, 'Tuumaenergia (kWh)', 0.0000),
                                                                                 (1, 'Tükkturvas (kWh)', 0.3697),
                                                                                 (1, 'Vedelgaas (LNG) (kWh)', 0.1990),
                                                                                 (1, 'Veeldatud naftagaas (LPG) (kWh)', 0.2287),
                                                                                 (2, 'Maanteesõiduki bensiin (l)', 2.247),
                                                                                 (2, 'Maanteesõiduki biodiisel FAME (l)', 0.148),
                                                                                 (2, 'Maanteesõiduki biodiisel HVO (l)', 0.003),
                                                                                 (2, 'Maanteesõiduki biodiisel ME (l)', 0.018),
                                                                                 (2, 'Maanteesõiduki diisel (l)', 2.636),
                                                                                 (2, 'Maanteesõiduki surubiometaan bio-CNG (kg)', 0.019),
                                                                                 (2, 'Maanteesõiduki surumaagaas CNG (kg)', 2.727),
                                                                                 (2, 'Maanteesõiduki veeldatud naftagaas LPG (kg)', 2.914),
                                                                                 (2, 'Rongidiisel (l)', 2.890),
                                                                                 (2, 'Veesõiduk - laevakütus (l)', 2.641),
                                                                                 (2, 'Õhusõiduk - lennukibensiin AVGAS 100LL (l)', 2.251),
                                                                                 (2, 'Õhusõiduk - petrooli tüüpi reaktiivkütus (l)', 2.361),
                                                                                 (3, 'Bensiin, kaubik (l)', 2.246),
                                                                                 (3, 'Bensiin, mootorratas (l)', 2.285),
                                                                                 (3, 'Bensiin, raskeveok (l)', 2.255),
                                                                                 (3, 'Bensiin, sõiduauto (l)', 2.246),
                                                                                 (3, 'Bio-CNG, kaubik (kg)', 0.019),
                                                                                 (3, 'Bio-CNG, raskeveok/buss (kg)', 0.021),
                                                                                 (3, 'Bio-CNG, sõiduauto (kg)', 0.019),
                                                                                 (3, 'CNG, kaubik (kg)', 2.727),
                                                                                 (3, 'CNG, raskeveok/buss (kg)', 2.728),
                                                                                 (3, 'CNG, sõiduauto (kg)', 2.727),
                                                                                 (3, 'Diisel, buss (l)', 2.648),
                                                                                 (3, 'Diisel, kaubik (l)', 2.636),
                                                                                 (3, 'Diisel, raskeveok (l)', 2.648),
                                                                                 (3, 'Diisel, sõiduauto (l)', 2.642),
                                                                                 (3, 'LPG, kaubik (kg)', 2.914),
                                                                                 (3, 'LPG, raskeveok/buss (kg)', 2.914),
                                                                                 (3, 'LPG, sõiduauto (kg)', 2.914),
                                                                                 (4, 'Bensiin või diisel, suurus teadmata', 0.189),
                                                                                 (4, 'Bensiin, keskmise suurusega (1,4–2,0 liitrine)', 0.199),
                                                                                 (4, 'Bensiin, suur (üle 2,0-liitrine)', 0.255),
                                                                                 (4, 'Bensiin, suurus teadmata', 0.197),
                                                                                 (4, 'Bensiin, väike (kuni 1,4-liitrine bensiinimootor)', 0.168),
                                                                                 (4, 'Diisel, keskmise suurusega (1,7–2,0-liitrine)', 0.162),
                                                                                 (4, 'Diisel, suur (üle 2,0-liitrine)', 0.217),
                                                                                 (4, 'Diisel, suurus teadmata', 0.185),
                                                                                 (4, 'Diisel, väike (kuni 1,7-liitrine diiselmootor)', 0.162),
                                                                                 (4, 'Hübriid, 1,4–2,0-liitrise bensiinimootoriga', 0.124),
                                                                                 (4, 'Hübriid, kuni 1,4-liitrise bensiinimootoriga', 0.120),
                                                                                 (4, 'Hübriid, suurus teadmata', 0.127),
                                                                                 (4, 'Hübriid, üle 2,0-liitrise bensiinimootoriga', 0.132),
                                                                                 (4, 'Kütus ja sõiduauto tüüp teadmata', 0.186),
                                                                                 (4, 'Pistikhübriid (bensiin) (keskmistatud)', 0.148),
                                                                                 (4, 'Pistikhübriid (diisel) (keskmistatud)', 0.139),
                                                                                 (4, 'Surubiometaan (bio-CNG) (keskmistatud)', 0.002),
                                                                                 (4, 'Surumaagaas (CNG) (keskmistatud)', 0.160),
                                                                                 (4, 'Veeldatud naftagaas (LPG) (keskmistatud)', 0.163);

INSERT INTO emission_factor (emission_factor_list_id, emission_type, factor) VALUES
                                                                                 (5, 'HCFE-235da2', 491),
                                                                                 (5, 'HFC-125 (R-125)', 3170),
                                                                                 (5, 'HFC-134 (R-134)', 1120),
                                                                                 (5, 'HFC-134a (R-134a)', 1300),
                                                                                 (5, 'HFC-143 (R-143)', 328),
                                                                                 (5, 'HFC-143a (R-143a)', 4800),
                                                                                 (5, 'HFC-152 (R-152)', 16),
                                                                                 (5, 'HFC-152a (R-152a)', 138),
                                                                                 (5, 'HFC-161 (R-161)', 4),
                                                                                 (5, 'HFC-227ea (R-227ea)', 3350),
                                                                                 (5, 'HFC-23 (R-23)', 12400),
                                                                                 (5, 'HFC-236cb (R-236cb)', 1210),
                                                                                 (5, 'HFC-236ea (R-236ea)', 1330),
                                                                                 (5, 'HFC-236fa (R-236fa)', 8060),
                                                                                 (5, 'HFC-245ca (R-245ca)', 716),
                                                                                 (5, 'HFC-245fa (R-245fa)', 858),
                                                                                 (5, 'HFC-32 (R-32)', 677),
                                                                                 (5, 'HFC-365mfc', 804),
                                                                                 (5, 'HFC-41 (R-41)', 116),
                                                                                 (5, 'HFC-43-10mee (R-4310)', 1650),
                                                                                 (5, 'HFE-125', 12400),
                                                                                 (5, 'HFE-134', 5560),
                                                                                 (5, 'HFE-143a', 523),
                                                                                 (5, 'HFE-236ca12 (HG-10)', 5350),
                                                                                 (5, 'HFE-245cb2', 654),
                                                                                 (5, 'HFE-245fa2', 812),
                                                                                 (5, 'HFE-338pcc13 (HG-01)', 2910),
                                                                                 (5, 'HFE-347mcc3', 530),
                                                                                 (5, 'HFE-347mcf2', 854),
                                                                                 (5, 'HFE-347pcf2', 889),
                                                                                 (5, 'HFE-356mec3', 387),
                                                                                 (5, 'HFE-356pcf2', 719),
                                                                                 (5, 'HFE-356pcc3', 413),
                                                                                 (5, 'HFE-356pcf3', 446),
                                                                                 (5, 'HFE-374pc2', 627),
                                                                                 (5, 'HFE-43-10pccc124 (H-Galden 1040x)', 2820),
                                                                                 (5, 'HFE-449sl (HFE-7100)', 421),
                                                                                 (5, 'HFE-569sf2 (HFE-7200)', 57),
                                                                                 (5, 'Lämmastiktrifluoriid', 16100),
                                                                                 (5, 'PFC-116 (perfluoroetaan)', 11100),
                                                                                 (5, 'PFC-14 (perfluorometaan)', 6630),
                                                                                 (5, 'PFC-218 (perfluoropropaan)', 8900),
                                                                                 (5, 'PFC-31-10 (perflourobutaan)', 9200),
                                                                                 (5, 'PFC-318 (perfluorotsüklobutaan)', 9540),
                                                                                 (5, 'PFC-41-12 (perfluoropentaan)', 8550),
                                                                                 (5, 'PFC-51-14 (perfluoroheksaan)', 7910),
                                                                                 (5, 'PFC-91-18 (perfluorodekaliin)', 7190),
                                                                                 (5, 'PFPMIE (perfluoropolümetüülisopropüül-eeter)', 9710),
                                                                                 (5, 'R-401A', 1130),
                                                                                 (5, 'R-401B', 1236),
                                                                                 (5, 'R-401C', 876),
                                                                                 (5, 'R-402A', 2571),
                                                                                 (5, 'R-402B', 2261),
                                                                                 (5, 'R-403B', 4457),
                                                                                 (5, 'R-404A', 3943),
                                                                                 (5, 'R-407A', 1923),
                                                                                 (5, 'R-407B', 2547),
                                                                                 (5, 'R-407C', 1624),
                                                                                 (5, 'R-407D', 1487),
                                                                                 (5, 'R-407E', 1425),
                                                                                 (5, 'R-407F', 1674),
                                                                                 (5, 'R-408A', 3257),
                                                                                 (5, 'R-410A', 1924),
                                                                                 (5, 'R-410B', 2048),
                                                                                 (5, 'R-411A', 1555),
                                                                                 (5, 'R-411B', 1659),
                                                                                 (5, 'R-4112', 8550),
                                                                                 (5, 'R-416A', 975),
                                                                                 (5, 'R-417A', 2127),
                                                                                 (5, 'R-417B', 2742),
                                                                                 (5, 'R-417C', 1643),
                                                                                 (5, 'R-419A', 2688),
                                                                                 (5, 'R-419B', 2162),
                                                                                 (5, 'R-420A', 1382),
                                                                                 (5, 'R-421A', 2385),
                                                                                 (5, 'R-421B', 2890),
                                                                                 (5, 'R-422A', 2847),
                                                                                 (5, 'R-422B', 2290),
                                                                                 (5, 'R-422C', 2795),
                                                                                 (5, 'R-422D', 2473),
                                                                                 (5, 'R-422E', 2350),
                                                                                 (5, 'R-423A', 2274),
                                                                                 (5, 'R-424A', 2212),
                                                                                 (5, 'R-425A', 1431),
                                                                                 (5, 'R-426A', 1371),
                                                                                 (5, 'R-427A', 2024),
                                                                                 (5, 'R-428A', 3417),
                                                                                 (5, 'R-429A', 15),
                                                                                 (5, 'R-430A', 106),
                                                                                 (5, 'R-431A', 42),
                                                                                 (5, 'R-434A', 3076),
                                                                                 (5, 'R-435A', 28),
                                                                                 (5, 'R-437A', 1639),
                                                                                 (5, 'R-438A', 2059),
                                                                                 (5, 'R-439A', 1829),
                                                                                 (5, 'R-444A', 89),
                                                                                 (5, 'R-445A', 118),
                                                                                 (5, 'R-500', 7564),
                                                                                 (5, 'R-503', 13300),
                                                                                 (5, 'R-507', 3985),
                                                                                 (5, 'R-507A', 3985),
                                                                                 (5, 'R-509', 4945),
                                                                                 (5, 'R-509A', 4945),
                                                                                 (5, 'R-512A', 196),
                                                                                 (5, 'Teadmata', 638),
                                                                                 (5, 'Trifluorometüülväävelpentafluoriid', 17400),
                                                                                 (5, 'Väävelheksafluoriid', 23500);
